---
- name: Install docker
  apt: name=docker.io state=present update_cache=yes

- name: add daemon.json for docker settings
  shell:
    cmd: |
      cat > /etc/docker/daemon.json <<EOF
      {
        "exec-opts": ["native.cgroupdriver=systemd"],
        "log-driver": "json-file",
        "log-opts": {
        "max-size": "100m"
        },
        "storage-driver": "overlay2",
        "storage-opts": [
        "overlay2.override_kernel_check=true"
        ]
      }       
      EOF
  args:
    executable: /bin/sh

- name: Add current users and admins to docker group
  user: name={{ansible_user}}
        groups=docker
        append=yes
  notify:
    - restart docker
